name: Cloudflare IP Updater

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  update_ip_list:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GIT_EMAIL: info@layer.web.tr

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install curl
        run: sudo apt-get install curl -y

      - name: Fetch Cloudflare IP list
        run: |
          ips=$(curl -s https://www.cloudflare.com/ips-v4/)
          echo "$ips" > CloudflareIPs.txt

      - name: Generate RouterOS script
        run: |
          routeros_script="/ip firewall address-list"
          while IFS= read -r ip; do
            routeros_script+="\nadd address=$ip list=CloudflareRoute"
          done < CloudflareIPs.txt
          echo -e "$routeros_script" > CloudflareRoute.rsc
          echo " " >> CloudflareRoute.rsc
          echo "## Updated $(date) - LAYERWEB.COM.TR Project" >> CloudflareRoute.rsc

      - name: Update Cloudflare Route script
        run: |
          cat CloudflareRoute.rsc > existing_cloudflare_route.rsc

      - name: Commit and push changes
        run: |
          git config --local user.email "${GIT_EMAIL}"
          git config --local user.name "ertugrulturan"
          git add CloudflareRoute.rsc
          git commit -m "Update Cloudflare IP list"
          git push
